import React from "react";
import LandingBackground from "../Images/bookwalk.jpg";
import "../style/Nav.css";
import "../style/LandingPage.css";

// import "../style/ViewProduct.css";

const LandingPage = () => {
  return (
    <>
      <img id="LandingIcon" src={LandingBackground} alt="Icon"></img>
      <div className="viewHeaderSection">
        <div className="viewIntro">
          BOOKS ABEND is a mock e-commerce website for online book purchases.
          Data has been generated by Faker to provide an ample seed of product
          data.
        </div>

        <ul className="listView">
          Things you can do as a user (logged in or as a guest):
          <li>Browse Products and add items to your cart</li>
          <li>Search Products by title or author</li>
          <li>Filter Products by Format and/or Category</li>
          <li>View Product Details for any Product</li>
          <li>View active cart items, including adding/deleting items</li>
          <li>Proceed to Checkout when you are finished shopping</li>
          <li>Login or Signup at any point while you are shopping</li>
        </ul>

        <ul className="listView">
          Things you can do as a logged in user:
          <li>All of the above actions</li>
          <li>
            When you log in, if you previously left unpurchased items in your
            cart, those items are added to your current shopping cart
          </li>
          <li>View your OrderHistory for previous orders</li>
          <li>View Order Details of any previous order.</li>
        </ul>
      </div>
    </>
  );
};

export default LandingPage;
